/**
 * RAG Document Entity
 *
 * This entity defines the structure for documents that will be stored in a vector database
 * for Retrieval-Augmented Generation (RAG) functionality.
 *
 * Future Integration:
 * - These documents will be embedded using models like OpenAI text-embedding-ada-002, Cohere, or similar
 * - Embeddings will be stored in a vector database (Pinecone, Weaviate, or FAISS)
 * - When users ask questions, their query will be embedded and similar documents will be retrieved
 * - Retrieved documents will provide context to an LLM for generating answers
 *
 * Use Cases:
 * - Exercise explanations and form tips
 * - Nutrition guidance
 * - IDF training protocols and military concepts
 * - Workout programming advice
 * - Injury prevention and recovery information
 */

export interface RAGDocument {
  // Unique identifier for the document
  id: string;

  // Document content
  content: string; // Main text content to be embedded
  contentEnglish?: string; // English translation (optional)

  // Metadata for filtering and categorization
  metadata: {
    // Document type
    type: 'exercise' | 'nutrition' | 'military' | 'training' | 'recovery' | 'general';

    // Category within type
    category?: string; // e.g., "strength", "cardio", "meal_planning", "tactical_concepts"

    // Language
    language: 'hebrew' | 'english' | 'both';

    // Source information
    source?: string; // e.g., "IDF Training Manual", "Exercise Database", "Nutrition Guide"
    sourceUrl?: string;

    // Relevance tags for better retrieval
    tags: string[]; // e.g., ["push-ups", "chest", "bodyweight"], ["protein", "muscle-building"]

    // Difficulty/level
    level?: 'beginner' | 'intermediate' | 'advanced' | 'elite';

    // Related entity IDs (for linking to exercises, workouts, etc.)
    relatedExerciseId?: string;
    relatedWorkoutId?: string;

    // Date information
    createdAt: string; // ISO date string
    updatedAt: string; // ISO date string
  };

  // Vector embedding (will be generated by embedding model)
  // This field will be populated during the embedding process
  embedding?: number[]; // Vector representation of the content

  // Optional fields for enhanced RAG
  title?: string; // Short title for the document
  summary?: string; // Brief summary (useful for displaying in UI)

  // Chunk information (for long documents split into chunks)
  chunkIndex?: number; // If document is split into chunks
  totalChunks?: number; // Total number of chunks for this document
  parentDocumentId?: string; // ID of the original document if this is a chunk
}

/**
 * RAG Query Interface
 *
 * Structure for queries sent to the RAG system
 */
export interface RAGQuery {
  // The user's question or search query
  query: string;

  // Language of the query
  language?: 'hebrew' | 'english';

  // Optional filters to narrow down results
  filters?: {
    type?: RAGDocument['metadata']['type'] | RAGDocument['metadata']['type'][];
    category?: string | string[];
    tags?: string[];
    level?: RAGDocument['metadata']['level'];
  };

  // Number of documents to retrieve
  topK?: number; // Default: 5

  // Minimum similarity score (0-1)
  minScore?: number; // Default: 0.7
}

/**
 * RAG Response Interface
 *
 * Structure for responses from the RAG system
 */
export interface RAGResponse {
  // The retrieved documents
  documents: RAGDocument[];

  // Relevance scores for each document (0-1)
  scores: number[];

  // Optional: Generated answer using the documents as context
  generatedAnswer?: string;

  // Query metadata
  query: string;
  resultsCount: number;
  processingTimeMs: number;
}

/**
 * RAG Document Service Class
 *
 * This is a placeholder for future RAG functionality.
 * In the future, this will handle:
 * - Document embedding
 * - Vector database operations
 * - Similarity search
 * - Context retrieval for LLM
 */
export class RAGDocument {
  /**
   * Create a new RAG document
   *
   * @param content - The text content to be embedded
   * @param metadata - Document metadata
   * @returns A new RAG document
   */
  static create(content: string, metadata: RAGDocument['metadata']): RAGDocument {
    return {
      id: crypto.randomUUID(),
      content,
      metadata: {
        ...metadata,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    };
  }

  /**
   * Prepare content for embedding
   *
   * This method cleans and formats content before sending to the embedding model
   *
   * @param content - Raw content
   * @returns Cleaned content ready for embedding
   */
  static prepareForEmbedding(content: string): string {
    // Remove extra whitespace
    let cleaned = content.trim().replace(/\s+/g, ' ');

    // Remove special characters that might confuse the embedding model
    // (Keep Hebrew characters, English letters, numbers, basic punctuation)
    cleaned = cleaned.replace(/[^\u0590-\u05FF\w\s.,;:!?()-]/g, '');

    return cleaned;
  }

  /**
   * Create a document from an Exercise entity
   *
   * This helper method converts an Exercise into a RAG document
   *
   * @param exercise - Exercise entity
   * @returns RAG document
   */
  static fromExercise(exercise: any): RAGDocument {
    const content = `
תרגיל: ${exercise.name}
קטגוריה: ${exercise.category}
רמת קושי: ${exercise.difficulty}
תיאור: ${exercise.description}
טיפים לביצוע: ${exercise.formTips?.join('. ')}
טעויות נפוצות: ${exercise.commonMistakes?.join('. ')}
שרירים מעורבים: ${exercise.targetMuscles?.join(', ')}
ציוד נדרש: ${exercise.equipment?.join(', ')}
    `.trim();

    return RAGDocument.create(content, {
      type: 'exercise',
      category: exercise.category,
      language: 'hebrew',
      tags: [
        exercise.name,
        ...exercise.targetMuscles || [],
        ...exercise.targetAttributes || [],
      ],
      level: exercise.difficulty,
      relatedExerciseId: exercise.id,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });
  }
}
